# Streamlit secrets configuration
# This file contains sensitive configuration that should not be committed to version control
# Copy this to your deployment environment and configure as needed

[database]
# Database connection strings (if needed)
# connection_string = "your_db_connection_here"

[api_keys]
# External API keys (if needed)
# openai_key = "your_openai_key"
# huggingface_token = "your_hf_token"

[aws]
# AWS credentials (if needed)
# access_key_id = "your_aws_access_key"
# secret_access_key = "your_aws_secret_key"
# region = "us-east-1"

[model]
# Model-specific configurations
checkpoint_path = "checkpoints/best_model.pth"
device = "auto"
cache_dir = "./cache"

[app]
# Application-specific settings
debug_mode = true
enable_profiling = false
max_concurrent_users = 10

# Note: This file should be added to .gitignore to keep secrets secure